// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// TODO: Add proof type:
// 1. TEE proof
// 2. ZKP proof
struct PreimageProofOutput {
    bytes32 dataHash;
    bool isValid;
}

struct TransferValidityProofOutput {
    bytes32 oldDataHash;
    bytes32 newDataHash;
    address receiver;
    bytes16 sealedKey;
    bool isValid;
}

interface IERC7857DataVerifier {
    /// @notice Verify preimage of data
    /// @param _proofs Proof generated by TEE/ZKP
    function verifyPreimage(
        bytes[] calldata _proofs
    ) external returns (PreimageProofOutput[] memory);

    /// @notice Verify data transfer validity
    /// @param _proofs Proof generated by TEE/ZKP
    function verifyTransferValidity(
        bytes[] calldata _proofs
    ) external returns (TransferValidityProofOutput[] memory);
}
